server:
  port : 8082

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            auto:
              offset:
                reset: earliest
      bindings:
        customers-in:
          destination: customers
          contentType: application/json
        moneylaundering-in:
          destination: moneylaundering
          contentType: application/json
