server:
  port : 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            auto:
              offset:
                reset: earliest
      bindings:
        transactions-in:
          destination: transactions
          contentType: application/json
